name: Publish Todoist Project (Python) to Pages

on:
  workflow_dispatch: {}
  schedule:
  # Poll ev 15 mins
    - cron: "*/15 * * * *"


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build static site
        env:
          TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
          # Provide ONE of these as repo secrets:
          TODOIST_PROJECT_ID: ${{ secrets.TODOIST_PROJECT_ID }}
          TODOIST_PROJECT_NAME: ${{ secrets.TODOIST_PROJECT_NAME }}
          EXCLUDE_PRIORITIES: ${{secrets.EXCLUDE_PRIORITIES}}
        run: python scripts/build.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
